### ISSUE TITLE
Normal and advanced users

### ISSUE THREAD

**Issue by Karyum** [WebAhead10/webahead-library-frontend#29]
Normal user is someone who can read documents and able to update the text. someone can be normal user by just registering through the website

Advanced user is someone who can read and update the documents text but also is able to cut the document into sections. for now only an admin can add a normal user.

For this we need to create a table called `users` table that contains the following columns:

1) id (int)
2) email (varchar)
3) password (varchar)
4) name (varchar)
5) created_at (date)
6) role   (enum of either `normal` or `advanced`)

### Tasks:

- [x] Create the `users` table
- [x] Create a controller that can add a normal user
- [x] _Edited_ Create 1 controller for both users, one will be for the normal user and one for the advanced user that will have a middleware which checks that only the admin can add them.

**Comment by Karyum** [comment]
the PR for this issue https://github.com/WebAhead10/webahead-library-backend/pull/16
